name: conda-vendor-dependencies
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - click
  - conda-lock>=1.2.1
  - packaging
  - requests
  - ruamel.yaml
  - setuptools>=43
  - wheel
  - pyyaml
  # solvers
  - conda
  - mamba
  - micromamba
  # test dependencies
  - pytest
  - pytest-mock

