name: conda-vendor-dependencies
channels:
  - conda-forge
dependencies:
  - python
  - click
  - conda-lock>=1.2.1
  - conda-build  
  - pip
  - ruamel.yaml
  # solvers
  - conda=4.12.0
  - mamba
  - micromamba
  # teset dependencies
  - pytest
  - pytest-mock
  - setuptools
  - wheel
  
